# Railway Deployment Configuration

[services]
  [[services.web]]
  name = "oq-ai-cyber"
  plan = "free"
  build_command = "pip install -r requirements.txt"
  start_command = "gunicorn main:app"
  auto_deploy = true
  region = "oregon"

  [services.web.env_vars]
  FLASK_ENV = "production"
